In [158]:
import numpy as np

def pivotamento(A, k, i):
    col = A[ i : n + 1, k ]

    colAbs = np.abs( col )
    print( 'colAbs \n', colAbs )

    indexMax = np.argmax( colAbs )
    print( indexMax )

    iChange = indexMax + i
    print( iChange )

    aux = np.copy( A[ k, : ] )
    print( "limha a ser movida",aux, )

    A[ k, : ] = np.copy( A[ iChange, : ] )
    A[ iChange, : ] = np.copy( aux )

    print(A ,'\n')
    return A



def troca_linha( A, b, n ): 
    for k in np.arange( 1, n ): 
        for i in np.arange( k + 1, n + 1 ): 
            A = pivotamento(A, k, i)
            m = A[ i, k ] / A[ k, k ]  
            A[ i, k ] = 0
        
    return A, b

Amat  = np.matrix([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])
Aarr  = np.array([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])
b=np.array([5, 6, 7, 15])
A = Aarr
print(A,'\n')
n = 3
x, y = troca_linha( A, b, n )
print(x)


[[ 3  2  4 -1]
 [ 0  1  0  3]
 [ 0 -3 -5  7]
 [ 0  2  4  0]] 

colAbs 
 [3 2]
0
2
limha a ser movida [0 1 0 3]
[[ 3  2  4 -1]
 [ 0 -3 -5  7]
 [ 0  1  0  3]
 [ 0  2  4  0]] 

colAbs 
 [2]
0
3
limha a ser movida [ 0 -3 -5  7]
[[ 3  2  4 -1]
 [ 0  2  4  0]
 [ 0  0  0  3]
 [ 0 -3 -5  7]] 

colAbs 
 [5]
0
3
limha a ser movida [0 0 0 3]
[[ 3  2  4 -1]
 [ 0  2  4  0]
 [ 0  0 -5  7]
 [ 0  0  0  3]] 

[[ 3  2  4 -1]
 [ 0  2  4  0]
 [ 0  0 -5  7]
 [ 0  0  0  3]]
[[ 3  2  4 -1]
 [ 0  2  4  0]
 [ 0  0 -5  7]
 [ 0  0  0  3]] 

colAbs 
 [0 0]
0
2
limha a ser movida [0 2 4 0]
[[ 3  2  4 -1]
 [ 0  0 -5  7]
 [ 0  2  4  0]
 [ 0  0  0  3]] 

colAbs 
 [0]
0
3
limha a ser movida [ 0  0 -5  7]
[[ 3  2  4 -1]
 [ 0  0  0  3]
 [ 0  0  4  0]
 [ 0  0 -5  7]] 

colAbs 
 [5]
0
3
limha a ser movida [0 0 4 0]
[[ 3  2  4 -1]
 [ 0  0  0  3]
 [ 0  0 -5  7]
 [ 0  0  4  0]] 

uahauha  [[ 3  2  4 -1]
 [ 0  0  0  3]
 [ 0  0 -5  7]
 [ 0  0  0  0]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:30: RuntimeWarning: divide by zero encountered in long_scalars
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:30: RuntimeWarning: invalid value encountered in long_scalars


In [155]:
#Duas condições
#Se elemento zero abaixo do pivô: continue. 
#Se um dos pivôs for zero mostrar mensagem de erro

def mats(a, b):
    n=len(a)
    for k in range (0, n-1, 1):
        if a[k][k] == 0:
            print('devido ao erro de pivo=0 o programa sera interrompido')
            break
        else:
            if a[k+1][k] == 0:
                continue
            for i in range (k+1, n, 1):
                m=a[i][k]/a[k][k]
                a[i][k]=0
                for j in range (k+1, n, 1):
                    a[i][j]=a[i][j]-(m*a[k][j])
                    b[i]=b[i]-m*b[k]
    return a1, b1                 



m3=np.array([[2, 1, -1], [-3, -1, 2], [-2, 1, 2]])
m4=np.array([8, -11, -3])
a1, b1=mats(m3, m4)
print('\n', m3)
print(matr(m3,m4))

devido ao erro de pivo=0 o programa sera interrompido

 [[ 2  1 -1]
 [ 0  0  0]
 [ 0  2  1]]
[-inf  inf  13.]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: divide by zero encountered in double_scalars
  del sys.path[0]
